FROM grafana/grafana-oss:11.2.2+security-01

# Copy the datasource configuration
COPY docker/grafana/provisioning/datasources/datasources.yml /etc/grafana/provisioning/datasources/datasources.yml
COPY docker/grafana/provisioning/dashboards/* /etc/grafana/provisioning/dashboards/*