FROM grafana/grafana-oss:12.3.3

# Copy the datasource configuration
COPY docker/grafana/provisioning/datasources/datasources.yml /etc/grafana/provisioning/datasources/datasources.yml
COPY docker/grafana/provisioning/dashboards/* /etc/grafana/provisioning/dashboards/*