apiVersion: 1
datasources:
  - name: timescaledb
    type: grafana-postgresql-datasource
    uid: PA942B37CCFAF5A81
    access: proxy
    url: timescaledb:5432
    jsonData:
      database: meshtastic
      sslmode: "disable"
      postgresVersion: 1600
      timescaledb: true
    user: postgres
    secureJsonData:
      password: postgres
    isDefault: true
    editable: true
